{-# OPTIONS --rewriting --guardedness #-}
module Conversion where

open import Data.Fin using (Fin; zero; suc)
open import Data.Nat using (ℕ; zero; suc)
open import Function using (_∘_)
open import Relation.Binary.PropositionalEquality using (_≡_; refl)

open import Types.Direction using (Dir; dual-dir)
import Types.IND1 as IND
import Types.COI as COI
import DualTail1 as DT
import DualStopAtMu as Stop

private
  variable
    n m : ℕ
    d : Dir
    T T₁ T₂ U U₁ U₂ : IND.Type n
    S R Q S₁ S₂ R₁ R₂ : IND.SType n
    G : IND.GType (suc n)
    H : IND.GType n
    alt alt' : Fin m → IND.SType n
    A B C : COI.Type
    F K L : COI.STypeF COI.SType
    X Y Z : COI.SType

----------------------------------------------------------------------
-- Syntactic conversion

-- The body of a recursive type is stored as a guarded communication head.
-- Unrolling substitutes the recursive type for the newest variable and then
-- embeds the exposed head back into the session syntax.
subst0 : IND.SType n → IND.Sub (suc n) n
subst0 S zero = S
subst0 S (suc x) = IND.var x

unroll : IND.GType (suc n) → IND.SType n
unroll G = IND.gdd (IND.substG (subst0 (IND.rec G)) G)

mutual
  -- Payload conversion is structural.  The only non-trivial call into session
  -- conversion is at channel payloads.
  data ConvT {n : ℕ} : IND.Type n → IND.Type n → Set where
    conv-unit :
      ConvT IND.TUnit IND.TUnit

    conv-int :
      ConvT IND.TInt IND.TInt

    conv-pair :
      ConvT T₁ U₁ →
      ConvT T₂ U₂ →
      ConvT (IND.TPair T₁ T₂) (IND.TPair U₁ U₂)

    conv-fun :
      ConvT T₁ U₁ →
      ConvT T₂ U₂ →
      ConvT (IND.TFun T₁ T₂) (IND.TFun U₁ U₂)

    conv-chan :
      ConvS S R →
      ConvT (IND.TChan S) (IND.TChan R)

  -- Session conversion is the inductive conversion relation used in the
  -- paper.  The stopped-duality axioms are included explicitly, but the
  -- adequacy lemmas below show that these axiom instances are also
  -- definitional equalities once the rewrite rules for Stop.dualS/dualG are
  -- enabled.
  data ConvS {n : ℕ} : IND.SType n → IND.SType n → Set where
    conv-refl :
      ConvS S S

    conv-symm :
      ConvS S R →
      ConvS R S

    conv-trans :
      ConvS S R →
      ConvS R Q →
      ConvS S Q

    conv-dual :
      ConvS S R →
      ConvS (Stop.dualS S) (Stop.dualS R)

    conv-unroll :
      ConvS (IND.rec G) (unroll G)

    conv-transmit :
      ConvT T U →
      ConvS S R →
      ConvS
        (IND.gdd (IND.transmit d T S))
        (IND.gdd (IND.transmit d U R))

    conv-choice :
      ((i : Fin m) → ConvS (alt i) (alt' i)) →
      ConvS
        (IND.gdd (IND.choice d m alt))
        (IND.gdd (IND.choice d m alt'))

    conv-end :
      ConvS (IND.gdd IND.end) (IND.gdd IND.end)

    conv-dual-end :
      ConvS (Stop.dualS (IND.gdd IND.end)) (IND.gdd IND.end)

    conv-dual-transmit :
      ConvS
        (Stop.dualS (IND.gdd (IND.transmit d T S)))
        (IND.gdd (IND.transmit (dual-dir d) T (Stop.dualS S)))

    conv-dual-choice :
      ConvS
        (Stop.dualS (IND.gdd (IND.choice d m alt)))
        (IND.gdd (IND.choice (dual-dir d) m (Stop.dualS ∘ alt)))

----------------------------------------------------------------------
-- Interpretation into the coinductive model

semT : IND.Type 0 → COI.Type
semT = DT.ind2coiT DT.ε

semS : IND.SType 0 → COI.SType
semS = DT.ind2coiS DT.ε

-- Coinductive duality is compatible with coinductive equivalence.
dual-cong :
  {S R : COI.SType} →
  S COI.≈ R →
  COI.dual S COI.≈ COI.dual R
dual-congF :
  {S R : COI.STypeF COI.SType} →
  S COI.≈' R →
  COI.dualF S COI.≈' COI.dualF R

COI.Equiv.force (dual-cong S≈R) =
  dual-congF (COI.Equiv.force S≈R)

dual-congF (COI.eq-transmit d T≈U S≈R) =
  COI.eq-transmit (dual-dir d) T≈U (dual-cong S≈R)
dual-congF (COI.eq-choice d S≈R) =
  COI.eq-choice (dual-dir d) (dual-cong ∘ S≈R)
dual-congF COI.eq-end =
  COI.eq-end

-- Adequacy of the stack interpretation for one syntactic unrolling step.
-- This is the semantic content of the μ-conversion rule; the stopped-duality
-- rules below do not need a corresponding semantic lemma because they reduce
-- definitionally by rewriting.
VarRelRen :
  DT.Stack {IND.GType} n →
  IND.Ren n m →
  DT.Stack {IND.GType} m →
  Set
VarRelRen σ ρ σ' =
  (x : Fin _) →
  DT.ind2coiS σ (IND.var x) COI.≈
  DT.ind2coiS σ' (IND.var (ρ x))

dropRel :
  (σ : DT.Stack {IND.GType} n) →
  (G : IND.GType (suc n)) →
  VarRelRen σ suc (DT.⟪ σ , G ⟫)
COI.Equiv.force (dropRel σ G x) = COI.≈'-refl

-- The unrolling proof only needs substitutions generated by replacing the
-- newest variable with its recursive type and then lifting that substitution
-- under nested binders.  Recording that shape as data exposes the decrease
-- hidden by a fully arbitrary variable-to-proof function.
data UnrollSubRel :
    DT.Stack {IND.GType} n →
    IND.Sub n m →
    DT.Stack {IND.GType} m →
    Set where
  root :
    (G : IND.GType 1) →
    UnrollSubRel
      (DT.⟪ DT.ε , G ⟫)
      (subst0 (IND.rec G))
      DT.ε

  lift :
    {θ : IND.Sub n m}
    {σ : DT.Stack {IND.GType} n}
    {σ' : DT.Stack {IND.GType} m} →
    UnrollSubRel σ θ σ' →
    (G : IND.GType (suc n)) →
    UnrollSubRel
      (DT.⟪ σ , G ⟫)
      (IND.liftSub θ)
      (DT.⟪ σ' , IND.substG (IND.liftSub θ) G ⟫)

-- A first-order record of the lifted renaming environments that arise under
-- recursive binders.  Making the binder spine explicit exposes the structural
-- decrease that was hidden in the old higher-order variable relation.
data RenEnv : ℕ → ℕ → Set where
  base-ren :
    (σ : DT.Stack {IND.GType} n) →
    (ρ : IND.Ren n m) →
    (σ' : DT.Stack {IND.GType} m) →
    VarRelRen σ ρ σ' →
    RenEnv n m

  push-ren :
    RenEnv n m →
    (G : IND.GType (suc n)) →
    RenEnv (suc n) (suc m)

ren-src : RenEnv n m → DT.Stack {IND.GType} n
ren-map : RenEnv n m → IND.Ren n m
ren-dst : RenEnv n m → DT.Stack {IND.GType} m

ren-src (base-ren σ ρ σ' rel) =
  σ
ren-src (push-ren env G) =
  DT.⟪ ren-src env , G ⟫

ren-map (base-ren σ ρ σ' rel) =
  ρ
ren-map (push-ren env G) =
  IND.liftRen (ren-map env)

ren-dst (base-ren σ ρ σ' rel) =
  σ'
ren-dst (push-ren env G) =
  DT.⟪ ren-dst env , IND.renameG (IND.liftRen (ren-map env)) G ⟫

ren-lhs : RenEnv n m → IND.SType n → COI.SType
ren-lhs env S =
  DT.ind2coiS (ren-src env) S

ren-rhs : RenEnv n m → IND.SType n → COI.SType
ren-rhs env S =
  DT.ind2coiS (ren-dst env) (IND.renameS (ren-map env) S)

-- The coalgebra used to prove renaming soundness.  A state is a syntactic
-- renaming obligation; known embeds an already established coinductive
-- equivalence, used for the initial assumptions about free variables.
data RenRel : COI.SType → COI.SType → Set where
  ren-state :
    (env : RenEnv n m) →
    (S : IND.SType n) →
    RenRel (ren-lhs env S) (ren-rhs env S)

  known :
    X COI.≈ Y →
    RenRel X Y

embedT :
  COI.EquivT COI.Equiv A B →
  COI.EquivT RenRel A B
embedF :
  COI.EquivF COI.Equiv F K →
  COI.EquivF RenRel F K

embedT COI.eq-unit =
  COI.eq-unit
embedT COI.eq-int =
  COI.eq-int
embedT (COI.eq-pair T≈A U≈B) =
  COI.eq-pair (embedT T≈A) (embedT U≈B)
embedT (COI.eq-fun T≈A U≈B) =
  COI.eq-fun (embedT T≈A) (embedT U≈B)
embedT (COI.eq-chan S≈R) =
  COI.eq-chan (known S≈R)

embedF (COI.eq-transmit d T≈A S≈R) =
  COI.eq-transmit d (embedT T≈A) (known S≈R)
embedF (COI.eq-choice d alts) =
  COI.eq-choice d (known ∘ alts)
embedF COI.eq-end =
  COI.eq-end

step :
  RenRel X Y →
  COI.EquivF RenRel (COI.SType.force X) (COI.SType.force Y)
stepG :
  (env : RenEnv n m) →
  (G : IND.GType n) →
  COI.EquivF RenRel
    (DT.ind2coiG (ren-src env) G)
    (DT.ind2coiG (ren-dst env) (IND.renameG (ren-map env) G))
stepT :
  (env : RenEnv n m) →
  (T : IND.Type n) →
  COI.EquivT RenRel
    (DT.ind2coiT (ren-src env) T)
    (DT.ind2coiT (ren-dst env) (IND.renameT (ren-map env) T))

step (known p) =
  embedF (COI.Equiv.force p)
step (ren-state env (IND.gdd G)) =
  stepG env G
step (ren-state env (IND.rec G)) =
  stepG (push-ren env G) G
step (ren-state (base-ren σ ρ σ' rel) (IND.var x)) =
  embedF (COI.Equiv.force (rel x))
step (ren-state (push-ren env G) (IND.var zero)) =
  step (ren-state env (IND.rec G))
step (ren-state (push-ren env G) (IND.var (suc x))) =
  step (ren-state env (IND.var x))

stepG env (IND.transmit d T S) =
  COI.eq-transmit d (stepT env T) (ren-state env S)
stepG env (IND.choice d m alt) =
  COI.eq-choice d (λ i → ren-state env (alt i))
stepG env IND.end =
  COI.eq-end

stepT env IND.TUnit =
  COI.eq-unit
stepT env IND.TInt =
  COI.eq-int
stepT env (IND.TPair T U) =
  COI.eq-pair (stepT env T) (stepT env U)
stepT env (IND.TFun T U) =
  COI.eq-fun (stepT env T) (stepT env U)
stepT env (IND.TChan S) =
  COI.eq-chan (ren-state env S)

close :
  RenRel X Y →
  X COI.≈ Y
closeT :
  COI.EquivT RenRel A B →
  COI.EquivT COI.Equiv A B
closeF :
  COI.EquivF RenRel F K →
  COI.EquivF COI.Equiv F K

COI.Equiv.force (close rel) =
  closeF (step rel)

closeT COI.eq-unit =
  COI.eq-unit
closeT COI.eq-int =
  COI.eq-int
closeT (COI.eq-pair T≈A U≈B) =
  COI.eq-pair (closeT T≈A) (closeT U≈B)
closeT (COI.eq-fun T≈A U≈B) =
  COI.eq-fun (closeT T≈A) (closeT U≈B)
closeT (COI.eq-chan S≈R) =
  COI.eq-chan (close S≈R)

closeF (COI.eq-transmit d T≈A S≈R) =
  COI.eq-transmit d (closeT T≈A) (close S≈R)
closeF (COI.eq-choice d alts) =
  COI.eq-choice d (close ∘ alts)
closeF COI.eq-end =
  COI.eq-end

-- Official renaming interface.  The extra RenEnv argument is confined to the
-- auxiliary coalgebra above, so callers see the same API as before.
rename-soundS :
  {ρ : IND.Ren n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  VarRelRen σ ρ σ' →
  (S : IND.SType n) →
  DT.ind2coiS σ S COI.≈ DT.ind2coiS σ' (IND.renameS ρ S)
rename-soundS {ρ = ρ} {σ = σ} {σ' = σ'} rel S =
  close (ren-state (base-ren σ ρ σ' rel) S)

rename-soundG :
  {ρ : IND.Ren n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  VarRelRen σ ρ σ' →
  (G : IND.GType n) →
  DT.ind2coiG σ G COI.≈' DT.ind2coiG σ' (IND.renameG ρ G)
rename-soundG {ρ = ρ} {σ = σ} {σ' = σ'} rel G =
  closeF (stepG (base-ren σ ρ σ' rel) G)

rename-soundT :
  {ρ : IND.Ren n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  VarRelRen σ ρ σ' →
  (T : IND.Type n) →
  COI.EquivT COI.Equiv
    (DT.ind2coiT σ T)
    (DT.ind2coiT σ' (IND.renameT ρ T))
rename-soundT {ρ = ρ} {σ = σ} {σ' = σ'} rel T =
  closeT (stepT (base-ren σ ρ σ' rel) T)

-- Substitution soundness uses the same coalgebraic pattern.  The relation has
-- one constructor for substitution obligations, embeds renaming obligations
-- for weakened substituted variables, and carries an explicit transitive case
-- so that the one-step coalgebra can compose the three links exposed by suc.
data SubRel : COI.SType → COI.SType → Set where
  sub-state :
    {θ : IND.Sub n m}
    {σ : DT.Stack {IND.GType} n}
    {σ' : DT.Stack {IND.GType} m} →
    UnrollSubRel σ θ σ' →
    (S : IND.SType n) →
    SubRel (DT.ind2coiS σ S) (DT.ind2coiS σ' (IND.substS θ S))

  sub-known :
    X COI.≈ Y →
    SubRel X Y

  sub-ren :
    RenRel X Y →
    SubRel X Y

  sub-trans :
    SubRel X Y →
    SubRel Y Z →
    SubRel X Z

sub-embedT :
  COI.EquivT COI.Equiv A B →
  COI.EquivT SubRel A B
sub-embedF :
  COI.EquivF COI.Equiv F K →
  COI.EquivF SubRel F K

sub-embedT COI.eq-unit =
  COI.eq-unit
sub-embedT COI.eq-int =
  COI.eq-int
sub-embedT (COI.eq-pair T≈A U≈B) =
  COI.eq-pair (sub-embedT T≈A) (sub-embedT U≈B)
sub-embedT (COI.eq-fun T≈A U≈B) =
  COI.eq-fun (sub-embedT T≈A) (sub-embedT U≈B)
sub-embedT (COI.eq-chan S≈R) =
  COI.eq-chan (sub-known S≈R)

sub-embedF (COI.eq-transmit d T≈A S≈R) =
  COI.eq-transmit d (sub-embedT T≈A) (sub-known S≈R)
sub-embedF (COI.eq-choice d alts) =
  COI.eq-choice d (sub-known ∘ alts)
sub-embedF COI.eq-end =
  COI.eq-end

ren-embedT :
  COI.EquivT RenRel A B →
  COI.EquivT SubRel A B
ren-embedF :
  COI.EquivF RenRel F K →
  COI.EquivF SubRel F K

ren-embedT COI.eq-unit =
  COI.eq-unit
ren-embedT COI.eq-int =
  COI.eq-int
ren-embedT (COI.eq-pair T≈A U≈B) =
  COI.eq-pair (ren-embedT T≈A) (ren-embedT U≈B)
ren-embedT (COI.eq-fun T≈A U≈B) =
  COI.eq-fun (ren-embedT T≈A) (ren-embedT U≈B)
ren-embedT (COI.eq-chan S≈R) =
  COI.eq-chan (sub-ren S≈R)

ren-embedF (COI.eq-transmit d T≈A S≈R) =
  COI.eq-transmit d (ren-embedT T≈A) (sub-ren S≈R)
ren-embedF (COI.eq-choice d alts) =
  COI.eq-choice d (sub-ren ∘ alts)
ren-embedF COI.eq-end =
  COI.eq-end

sub-transT :
  COI.EquivT SubRel A B →
  COI.EquivT SubRel B C →
  COI.EquivT SubRel A C
sub-transF :
  COI.EquivF SubRel F K →
  COI.EquivF SubRel K L →
  COI.EquivF SubRel F L

sub-transT COI.eq-unit COI.eq-unit =
  COI.eq-unit
sub-transT COI.eq-int COI.eq-int =
  COI.eq-int
sub-transT (COI.eq-pair T≈A U≈B) (COI.eq-pair A≈C B≈D) =
  COI.eq-pair (sub-transT T≈A A≈C) (sub-transT U≈B B≈D)
sub-transT (COI.eq-fun T≈A U≈B) (COI.eq-fun A≈C B≈D) =
  COI.eq-fun (sub-transT T≈A A≈C) (sub-transT U≈B B≈D)
sub-transT (COI.eq-chan S≈R) (COI.eq-chan R≈Q) =
  COI.eq-chan (sub-trans S≈R R≈Q)

sub-transF (COI.eq-transmit d T≈A S≈R) (COI.eq-transmit .d A≈C R≈Q) =
  COI.eq-transmit d (sub-transT T≈A A≈C) (sub-trans S≈R R≈Q)
sub-transF (COI.eq-choice d S≈R) (COI.eq-choice .d R≈Q) =
  COI.eq-choice d (λ i → sub-trans (S≈R i) (R≈Q i))
sub-transF COI.eq-end COI.eq-end =
  COI.eq-end

sub-step :
  SubRel X Y →
  COI.EquivF SubRel (COI.SType.force X) (COI.SType.force Y)
sub-stepVar :
  {θ : IND.Sub n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  UnrollSubRel σ θ σ' →
  (x : Fin n) →
  COI.EquivF SubRel
    (COI.SType.force (DT.ind2coiS σ (IND.var x)))
    (COI.SType.force (DT.ind2coiS σ' (θ x)))
sub-stepG :
  {θ : IND.Sub n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  UnrollSubRel σ θ σ' →
  (G : IND.GType n) →
  COI.EquivF SubRel
    (DT.ind2coiG σ G)
    (DT.ind2coiG σ' (IND.substG θ G))
sub-stepT :
  {θ : IND.Sub n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  UnrollSubRel σ θ σ' →
  (T : IND.Type n) →
  COI.EquivT SubRel
    (DT.ind2coiT σ T)
    (DT.ind2coiT σ' (IND.substT θ T))

sub-step (sub-known p) =
  sub-embedF (COI.Equiv.force p)
sub-step (sub-ren rel) =
  ren-embedF (step rel)
sub-step (sub-trans rel₁ rel₂) =
  sub-transF (sub-step rel₁) (sub-step rel₂)
sub-step (sub-state rel (IND.gdd G)) =
  sub-stepG rel G
sub-step (sub-state rel (IND.rec G)) =
  sub-stepG (lift rel G) G
sub-step (sub-state rel (IND.var x)) =
  sub-stepVar rel x

sub-stepVar (root G) zero =
  sub-embedF COI.≈'-refl
sub-stepVar (lift rel G) zero =
  sub-stepG (lift rel G) G
sub-stepVar (lift {θ = θ} {σ = σ} {σ' = σ'} rel G) (suc x) =
  sub-transF
    (sub-transF
      (sub-embedF (COI.Equiv.force (COI.≈-symm (dropRel σ G x))))
      (sub-stepVar rel x))
    (ren-embedF
      (step
        (ren-state
          (base-ren
            σ'
            suc
            (DT.⟪ σ' , IND.substG (IND.liftSub θ) G ⟫)
            (dropRel σ' (IND.substG (IND.liftSub θ) G)))
          (θ x))))

sub-stepG rel (IND.transmit d T S) =
  COI.eq-transmit d (sub-stepT rel T) (sub-state rel S)
sub-stepG rel (IND.choice d m alt) =
  COI.eq-choice d (λ i → sub-state rel (alt i))
sub-stepG rel IND.end =
  COI.eq-end

sub-stepT rel IND.TUnit =
  COI.eq-unit
sub-stepT rel IND.TInt =
  COI.eq-int
sub-stepT rel (IND.TPair T U) =
  COI.eq-pair (sub-stepT rel T) (sub-stepT rel U)
sub-stepT rel (IND.TFun T U) =
  COI.eq-fun (sub-stepT rel T) (sub-stepT rel U)
sub-stepT rel (IND.TChan S) =
  COI.eq-chan (sub-state rel S)

sub-close :
  SubRel X Y →
  X COI.≈ Y
sub-closeT :
  COI.EquivT SubRel A B →
  COI.EquivT COI.Equiv A B
sub-closeF :
  COI.EquivF SubRel F K →
  COI.EquivF COI.Equiv F K

COI.Equiv.force (sub-close rel) =
  sub-closeF (sub-step rel)

sub-closeT COI.eq-unit =
  COI.eq-unit
sub-closeT COI.eq-int =
  COI.eq-int
sub-closeT (COI.eq-pair T≈A U≈B) =
  COI.eq-pair (sub-closeT T≈A) (sub-closeT U≈B)
sub-closeT (COI.eq-fun T≈A U≈B) =
  COI.eq-fun (sub-closeT T≈A) (sub-closeT U≈B)
sub-closeT (COI.eq-chan S≈R) =
  COI.eq-chan (sub-close S≈R)

sub-closeF (COI.eq-transmit d T≈A S≈R) =
  COI.eq-transmit d (sub-closeT T≈A) (sub-close S≈R)
sub-closeF (COI.eq-choice d alts) =
  COI.eq-choice d (sub-close ∘ alts)
sub-closeF COI.eq-end =
  COI.eq-end

-- Official substitution interface.  The coalgebra carries the extra structure;
-- the exported lemmas keep the old argument shape.
lookupSub :
  {θ : IND.Sub n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  UnrollSubRel σ θ σ' →
  (x : Fin n) →
  DT.ind2coiS σ (IND.var x) COI.≈ DT.ind2coiS σ' (θ x)
lookupSub rel x =
  sub-close (sub-state rel (IND.var x))

subst-soundS :
  {θ : IND.Sub n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  UnrollSubRel σ θ σ' →
  (S : IND.SType n) →
  DT.ind2coiS σ S COI.≈ DT.ind2coiS σ' (IND.substS θ S)
subst-soundS rel S =
  sub-close (sub-state rel S)

subst-soundG :
  {θ : IND.Sub n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  UnrollSubRel σ θ σ' →
  (G : IND.GType n) →
  DT.ind2coiG σ G COI.≈' DT.ind2coiG σ' (IND.substG θ G)
subst-soundG rel G =
  sub-closeF (sub-stepG rel G)

subst-soundT :
  {θ : IND.Sub n m} {σ : DT.Stack {IND.GType} n}
  {σ' : DT.Stack {IND.GType} m} →
  UnrollSubRel σ θ σ' →
  (T : IND.Type n) →
  COI.EquivT COI.Equiv
    (DT.ind2coiT σ T)
    (DT.ind2coiT σ' (IND.substT θ T))
subst-soundT rel T =
  sub-closeT (sub-stepT rel T)

unroll-sound :
  {G : IND.GType 1} →
  semS (IND.rec G) COI.≈ semS (unroll G)
COI.Equiv.force (unroll-sound {G = G}) =
  subst-soundG (root G) G

mutual
  convT-sound :
    {T U : IND.Type 0} →
    ConvT T U →
    COI.EquivT COI.Equiv (semT T) (semT U)

  convS-sound :
    {S R : IND.SType 0} →
    ConvS S R →
    semS S COI.≈ semS R

  convT-sound conv-unit =
    COI.eq-unit
  convT-sound conv-int =
    COI.eq-int
  convT-sound (conv-pair T₁≈U₁ T₂≈U₂) =
    COI.eq-pair (convT-sound T₁≈U₁) (convT-sound T₂≈U₂)
  convT-sound (conv-fun T₁≈U₁ T₂≈U₂) =
    COI.eq-fun (convT-sound T₁≈U₁) (convT-sound T₂≈U₂)
  convT-sound (conv-chan S≈R) =
    COI.eq-chan (convS-sound S≈R)

  convS-sound conv-refl =
    COI.≈-refl
  convS-sound (conv-symm S≈R) =
    COI.≈-symm (convS-sound S≈R)
  convS-sound (conv-trans S≈R R≈Q) =
    COI.≈-trans (convS-sound S≈R) (convS-sound R≈Q)
  convS-sound (conv-dual {S = S} {R = R} S≈R) =
    COI.≈-trans
      (COI.≈-symm (Stop.ground S))
      (COI.≈-trans (dual-cong (convS-sound S≈R)) (Stop.ground R))
  convS-sound conv-unroll =
    unroll-sound
  COI.Equiv.force (convS-sound (conv-transmit T≈U S≈R)) =
    COI.eq-transmit _ (convT-sound T≈U) (convS-sound S≈R)
  COI.Equiv.force (convS-sound (conv-choice S≈R)) =
    COI.eq-choice _ (λ i → convS-sound (S≈R i))
  convS-sound conv-end =
    COI.≈-refl
  convS-sound conv-dual-end =
    COI.≈-refl
  convS-sound conv-dual-transmit =
    COI.≈-refl
  convS-sound conv-dual-choice =
    COI.≈-refl

----------------------------------------------------------------------
-- Definitional adequacy of the stopped-duality conversion axioms

dual-gdd-definitional :
  {G : IND.GType n} →
  Stop.dualS (IND.gdd G) ≡ IND.gdd (Stop.dualG G)
dual-gdd-definitional = refl

dual-end-definitional :
  Stop.dualS (IND.gdd (IND.end {n = n})) ≡ IND.gdd IND.end
dual-end-definitional = refl

dual-transmit-definitional :
  Stop.dualS (IND.gdd (IND.transmit d T S)) ≡
  IND.gdd (IND.transmit (dual-dir d) T (Stop.dualS S))
dual-transmit-definitional = refl

dual-choice-definitional :
  Stop.dualS (IND.gdd (IND.choice d m alt)) ≡
  IND.gdd (IND.choice (dual-dir d) m (Stop.dualS ∘ alt))
dual-choice-definitional = refl

-- The same facts at the conversion-judgment level: the computational
-- conversion axioms can be witnessed by reflexivity, because the two sides
-- are definitionally equal after rewriting.
dual-end-adequacy :
  ConvS (Stop.dualS (IND.gdd (IND.end {n = n}))) (IND.gdd IND.end)
dual-end-adequacy = conv-refl

dual-transmit-adequacy :
  ConvS
    (Stop.dualS (IND.gdd (IND.transmit d T S)))
    (IND.gdd (IND.transmit (dual-dir d) T (Stop.dualS S)))
dual-transmit-adequacy = conv-refl

dual-choice-adequacy :
  ConvS
    (Stop.dualS (IND.gdd (IND.choice d m alt)))
    (IND.gdd (IND.choice (dual-dir d) m (Stop.dualS ∘ alt)))
dual-choice-adequacy = conv-refl
